---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - name: hello-world-nodejs
        image: quay.io/appvia_hub_dev/hello-world-demo:latest
        ports:
          - containerPort: 4000
